<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Hotels_la la-plane mx-1</name>
   <tag></tag>
   <elementGuidId>1696f84e-f9b8-4a44-95f0-a48f21e02b9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.la.la-plane.mx-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id='hotels-tab']/span/i)[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>la la-plane mx-1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Tab&quot;)/li[@class=&quot;nav-item&quot;]/button[@id=&quot;hotels-tab&quot;]/span[@class=&quot;d-xl-none d-lg-none&quot;]/i[@class=&quot;la la-plane mx-1&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//button[@id='hotels-tab']/span/i)[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/button/span/i</value>
   </webElementXpaths>
</WebElementEntity>
